### ISSUE TITLE
Make LCLS-Specific Assumptions Configurable

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/lightpath#109]
## Expected Behavior

Any light source should be able to use lightpath, provided they know how their devices should be ordered and they satisfy the API

## Current Behavior

Required to use happi that sorts on z, beamline

## Possible Solution

Lightpath config file that picks which happi parameter to use for sorting sections, and which happi parameter to use for deciding what each section is

## Context

It's not simple to use this outside of LCLS for collaborative efforts

**Comment by klauer** [comment]
(Based on Slack discussions) - we noted that while a directed, acyclic graph makes sense for LCLS, it absolutely does not make sense for a synchrotron facility. At best, we can say just a "directed graph".

Appropriate data structures and utilities to navigate them are a must here.

**Comment by tangkong** [comment]
To add onto this, we should probably allow users to configure:

- minimum transmission
- endstations (supply their own [beamlines](https://github.com/pcdshub/lightpath/blob/bebc618c1651605b9af27e0f5cf676b40b8fc3d1/lightpath/config.py#L8-L16) dictionary)
