### ISSUE TITLE
Add TMO, RIX, TXI beamline definitions to config

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/lightpath#117]
These beamline definitions are missing. Other repos currently leech off of the beamline definitions, so filling these in is needed. This is also needed here in order to enable hutch lightpaths.

The beamline definitions should eventually migrate out into a different repo, but they are here for now so let's fix them here.

**Comment by tangkong** [comment]
This was fixed by reworking the app to build a facility graph and calculate paths from there.  Efforts have been scattered across #133 and other PR's, but lightpath now supports all beamlines
