### ISSUE TITLE
Consider splitting into two independently installable packages

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/lightpath#180]
## Expected Behavior

It would be nice for testing/CI and maybe even some applications to be able to build with a lightpath dependency for the dataclasses and internals but not need to include pydm or pyqt because the UI isn't going to be used.

It's not clear to me that this is worth the effort but I thought it would be an interesting thing to propose:
- `lightpath-base`: includes the non-gui elements and non-gui dependencies
- `lightpath`: includes the gui elements, depends on `lightpath-base`, `typhos`, `pydm`, etc.

## Current Behavior

One big installable package, gui and logic

## Possible Solution

I'm not actually sure the best way to accomplish something like this, maybe look to other packages for inspiration.

## Context

A lot of our CI python 3.11 builds fail on environment creation due to an inclusion of pydm/pyqt even though these aren't tested in those builds.

**Comment by ZLLentz** [comment]
Currently, only the `ui` submodule and `main.py` import qt-related dependencies.

**Comment by tangkong** [comment]
I think we can look to [matplotlib](https://github.com/conda-forge/matplotlib-feedstock/blob/5af510232c2fa984e981e3eeb18128a6cab41b6d/recipe/meta.yaml#L69-L82) for inspiration here.  They have a `matplotlib-base` and `matplotlib` package that adds pyqt as a dependency.

on the pip side ... I'm not exactly sure what happens yet
