### ISSUE TITLE
Fixed order of beamlines in UI

### ISSUE THREAD

**Issue by teddyrendahl** [pcdshub/lightpath#25]
User interface has a non-sensical order. It currently sorts by the start of each path, but since the prior path is appended to the subsequent ones, they all have the same start. We should sort by end point

**Comment by tangkong** [comment]
This is... maybe not so relevant anymore.  We no longer sort the paths, and path loading has been made lazy (so sorting by endpoint is not an option) closed by #150, to choose a PR
