### ISSUE TITLE
Startup script

### ISSUE THREAD

**Issue by teddyrendahl** [pcdshub/lightpath#56]
## Expected Behavior

We should be able to have a `lightpath` executable that takes a `happi` configuration file and displays a GUI.

## Current Behavior

This is boilerplate code that has to be repeated in launch scripts.

```python
from PyQt5.QtGui import QApplication
from lightpath import Controller
from lightpath.ui import LightApp

app = QApplication()
light = LightApp(Controller('path/to/db.json'))
light.exec_()
```

**Comment by ZLLentz** [comment]
+1 Jason asked for this

**Comment by teddyrendahl** [comment]
@ZLLentz for what application?

**Comment by ZLLentz** [comment]
He wanted to run the lightpath, but the only way to launch it right now is through the old skywalker stuff
