### ISSUE TITLE
Show position in screen instead of inserted/removed

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/lightpath#58]
It has been requested multiple times to have the attenuator show it's attenuation value, the slits show their openness, etc. in the gui.

My suggestion is to use the `position` attribute to display the text, and use `inserted` and `removed` to color it. This covers all the devices where we care about some number more than we care about `inserted` or `removed`, and gives more information for things like the pulse picker which can be `OPEN`, `CLOSED`, `OUT`

**Comment by teddyrendahl** [comment]
I agree. The `lightpath` was written before we had standardized the `StatePositioner` class. This greatly helps make the UI more specific.

**Comment by teddyrendahl** [comment]
@ZLLentz thoughts on using the `hints` instead of `position`. Benefits are I can subscribe directly to the `hinted` signals and use `PyDM` widgets.

**Comment by ZLLentz** [comment]
Seems reasonable. I think we floated this idea before there were "hinted" signals to subscribe to. The new interface makes this slightly nicer. We're also dropping the assumption of a `position` attribute.
