### ISSUE TITLE
Create LightPath IOC

### ISSUE THREAD

**Issue by klauer** [pcdshub/lightpath#99]
Mostly a placeholder for ideas. Keeping in mind that I know nothing about the lightpath codebase as of yet...

Ideas:
* Maybe PVs like: 
`...:LightPath:$(happi_name):HasBeam`

* And/or a matrix of devices for ease of display creation, where the PV value indicates if beam transmission goes up to (device1) and continues to (device2):
`...:LightPath:$(happi_name1):$(happi_name2):BeamTransmission`

**Comment by ZLLentz** [comment]
This may need to be a caproto IOC if we're generating PV names based on device lookups

**Comment by klauer** [comment]
I'd say this is probably a "will not do" sort of thing. @tangkong ?

**Comment by tangkong** [comment]
Agreed, I think it's an interesting idea but not on the roadmap for now
